version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    parallelism: 4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - .
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  lint:
      docker:
        - image: circleci/node:10
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
        - run: yarn lint
  lint-sass:
      docker:
        - image: circleci/node:10
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
        - run: yarn sass-lint
workflows:
  version: 2.1
  pipeline:
    jobs:
      - build
      - lint
      - lint-sass
